version: '3.8'

services:
  # this is our kafka cluster.
  kafka-cluster:
    image: landoop/fast-data-dev:cp3.3.0
    networks:
      - dev-network
    environment:
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
      FORWARDLOGS: 0              # Disable running 5 file source connectors that bring application logs into Kafka topics
      SAMPLEDATA: 0               # Do not create sea_vessel_position_reports, nyc_yellow_taxi_trip_data, reddit_posts topics with sample Avro records.
    ports:
      - '2181:2181'                 # Zookeeper
      - '3030:3030'                 # Landoop UI
      - '8081-8083:8081-8083'       # REST Proxy, Schema Registry, Kafka Connect ports
      - '9581-9585:9581-9585'       # JMX Ports
      - '9092:9092'                 # Kafka Broker

  zipkin-server:
    image: openzipkin/zipkin
    networks:
      - dev-network
    ports:
      - '9411:9411'
    restart: always #Restart if there is a problem starting up

  producer:
    image: ms-clients-producer
    build:
      context: .
      dockerfile: ./ms-clients/Dockerfile
    networks:
      - dev-network
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: local
      KAFKA-PRODUCER-CONFIG_BOOTSTRAP-SERVERS: 'http://kafka-cluster:9092'
      KAFKA-PRODUCER-CONFIG_SCHEMA-REGISTRY-URL: 'http://kafka-cluster:8081/'
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: 'http://zipkin-server:9411/api/v2/spans'
    depends_on:
      - kafka-cluster
      - zipkin-server

  consumer:
    image: ms-clients-consumer
    build: consumer/.
    networks:
      - dev-network
    ports:
      - '8079:8079'
    environment:
      KAFKA-CONFIG_BOOTSTRAP-SERVERS: 'http://kafka-cluster:9092'
      KAFKA-CONFIG_SCHEMA-REGISTRY-URL: 'http://kafka-cluster:8081/'
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: 'http://zipkin-server:9411/api/v2/spans'
    depends_on:
      - kafka-cluster
      - zipkin-server
networks:
  dev-network: